# Generated by Django 3.1.1 on 2021-05-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ssim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_original', models.ImageField(default='default.png', upload_to='images/')),
                ('image_result', models.ImageField(default='default.png', upload_to='images/')),
                ('username', models.CharField(default='Anonim', max_length=255)),
                ('ssim', models.FloatField(default='0', max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
