# Generated by Django 3.1.1 on 2020-12-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='images')),
                ('action', models.CharField(choices=[('ENKRIPSI', 'enkripsi'), ('DESKRIPSI', 'deskripsi')], default='ENKRIPSI', max_length=50)),
                ('kunci_a', models.IntegerField()),
                ('kunci_b', models.IntegerField()),
                ('kunci_c', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
