# Generated by Django 3.1.1 on 2020-12-03 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20201203_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crypto',
            old_name='kunci_c',
            new_name='kunci_d',
        ),
    ]
