# Generated by Django 3.1.1 on 2020-12-03 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_auto_20201203_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='kunci_a',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='kunci_b',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='kunci_d',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
