# Generated by Django 3.1.1 on 2020-12-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_auto_20201203_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='username',
            field=models.CharField(default='Anonim', max_length=255),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
    ]
