# Generated by Django 3.1.1 on 2020-12-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_auto_20201203_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='durasi',
            field=models.FloatField(default='0', max_length=255),
        ),
    ]
