# Generated by Django 3.1.1 on 2021-04-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0007_crypto_durasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='psnr',
            field=models.FloatField(default='0', max_length=255),
        ),
    ]
