# Generated by Django 3.1.1 on 2021-04-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0008_crypto_psnr'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='image_ori',
            field=models.FloatField(default='0'),
        ),
    ]
