# Generated by Django 3.1.1 on 2021-04-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0009_crypto_image_ori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='image_ori',
            field=models.CharField(default='0', max_length=9999999),
        ),
    ]
