# Generated by Django 3.1.1 on 2021-04-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0010_auto_20210430_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='image_ori',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
