# Generated by Django 3.1.1 on 2021-05-01 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0011_auto_20210430_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='image_ori',
        ),
    ]
